app_profile/urls.py
from django.conf.urls import url
from .views import index, editProfile, integrateData, addKeahlian

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit-profile/$', editProfile, name='edit-profile'),
    url(r'^add-keahlian/$', addKeahlian, name='add-keahlian'),

    url(r'^integrate/$', integrateData, name='integrate')
    ]

tp2ppw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_login.urls as app_login
import app_status.urls as app_status
import app_riwayat.urls as app_riwayat
import app_profile.urls as profile
import app_carimahasiswa.urls as app_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(app_login,namespace='login')),
    url(r'^status/', include(app_status,namespace='status')),
    url(r'^app-riwayat/', include(app_riwayat,namespace='app-riwayat')),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^carimahasiswa/', include(app_carimahasiswa,namespace='carimahasiswa')),
    url(r'^$', RedirectView.as_view(url = "/login/", permanent = "true"), name = 'index'),
]

app_profile/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
# Create your models here.
class Pengguna(models.Model):
	nama = models.TextField()
	npm = models.TextField()
	email = models.TextField()
	profile = models.TextField()

class Keahlian(models.Model):
	jenis = models.TextField()
	level = models.TextField()
	pengguna = models.ForeignKey(Pengguna, on_delete = models.CASCADE)

app_profile/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Pengguna,Keahlian

# Create your views here.
response = {}
def index(request):
	if 'user_login' in request.session:
		html = 'app_profile/profile.html'
		response['npm'] = request.session['kode_identitas']
		getDataFromModel(request)
		return render(request, html,response)
	else:
		HttpResponseRedirect(reverse('login'))

def editProfile(request):
	if 'user_login' in request.session:
		html = 'app_profile/edit_profile.html'
		response['npm'] = request.session['kode_identitas']
		getDataFromModel(request)
		return render(request, html,response)
	else:
		HttpResponseRedirect(reverse('login'))
def integrateData(request):
	if(request.method == 'POST'):
		nama = request.POST.get('first-name') +' '+request.POST.get('last-name')
		npm = request.session['kode_identitas']
		email = request.POST.get('email')
		profile = request.POST.get('link')
		pengguna = Pengguna(nama = nama, npm = npm, email = email, profile = profile)
		HttpResponseRedirect(reverse('profile:edit-profile'))

def addKeahlian(request):
	if(request.method == 'POST' and isIntegrated()):
		pengguna = Pengguna.objects.filter(npm = request.session['kode_identitas'])[0]
		keahlian = Keahlian(jenis = request.POST.get('keahlian'), level = request.POST.get('level'), pengguna = pengguna)
		keahlian.save()
		HttpResponseRedirect(reverse('profile:edit-profile'))

def getDataFromModel(request):
	jumlah = Pengguna.objects.all().count()
	if(jumlah > 0):
		pengguna = Pengguna.objects.filter(npm = request.session['kode_identitas'])[0]
		keahlian = Keahlian.objects.filter(pengguna = pengguna)
		response['name'] = pengguna.name
		response['npm'] = pengguna.npm
		response['email'] = pengguna.email
		response['link'] = pengguna.profile
		response['linked'] = True
		response['keahlian'] = keahlian

	else:
		response['name'] = 'kosong'
		response['npm'] = 'kosong'
		response['email'] = 'kosong'
		response['link'] = 'kosong'
def isIntegrated():
	jumlah = Pengguna.objects.all().count()
	return jumlah > 0

app_profile/templates/app_profile/edit_profile.html
<img src="https://cdn1.iconfinder.com/data/icons/user-pictures/101/malecostume-512.png">
<button>Simpan</button>
<button href="{% url 'profile'%}">Keluar</button>
<p>NPM:{{npm}}</p>
<p>Data Pribadi</p>
{% if linked %}
	<p>
		Nama : {{name}}
		Email : {{email}}
		Profile LinkedIn: {{profile}}
	</p>
{% else %}
<script type="in/Login"></script>
{% endif %}

<form method="POST" action="{% url 'profile:add-keahlian' %}" class="form-inline">
    <label> Keahlian </label> <input type="text" class="form-control" name="keahlian" placeholder="keahlian">
    <label> Level </label> <input type="text" class="form-control" name="level" placeholder="level">
    <input type="submit" class="btn btn-primary pull-right">
</form>

<ul>
	{% for item in keahlian%}
	<li>{{item.jenis}} - {{item.level}}</li>
	{% endfor %}
</ul>

app_profile/templates/app_profile/profile.html
{% extends "app_riwayat/layout/base.html" %}
{% load staticfiles%}

{% block content %}


<p>Nama: {{name}}</p>
<p>NPM: {{npm}}</p>
<ul>
	{% for item in keahlian%}
	<li>{{item.jenis}} - {{item.level}}</li>
	{% endfor %}
</ul>
<p>Email: {{email}}</p>
<p>Profile LinkedIn: {{link}}</p>

{% endblock%}