app_login/urls.py
from django.conf.urls import url
from .views import index

from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


    # index
    url(r'^$', index, name='index'),

]

tp2ppw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_login.urls as app_login
import app_status.urls as app_status
import app_riwayat.urls as app_riwayat
import app_profile.urls as profile
import app_carimahasiswa.urls as app_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(app_login,namespace='login')),
    url(r'^status/', include(app_status,namespace='status')),
    url(r'^app-riwayat/', include(app_riwayat,namespace='app-riwayat')),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^carimahasiswa/', include(app_carimahasiswa,namespace='carimahasiswa')),
    url(r'^$', RedirectView.as_view(url = "/login/", permanent = "true"), name = 'index'),
]

app_login/models.py
from django.db import models

# Create your models here.

app_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

response = {}

def index(request):
	response['author'] = "Kelompok 5 C"
	if 'user_login' in request.session:
		response['author'] = get_data_user(request, 'user_login')
		return HttpResponseRedirect(reverse('profile:index'))
	else:
		response['author'] = get_data_user(request, 'user_login')
		html = 'app_login/login.html'
		return render(request, html, response)

def get_data_user(request, tipe):
	data = None
	if tipe == "user_login" and 'user_login' in request.session:
		data = request.session['user_login']
	return data

app_login/templates/app_login/partials/footer.html
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p style="color: green; text-align: center; position:fixed; bottom : 0; width : 100%;">&copy; Made with Love by Kelompok 5 C</p>

app_login/templates/app_login/partials/header.html
<nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'login:index' %}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li id = "LogOutBut"></li>
    </ul>
  </div>
</nav>