app_login/urls.py
from django.conf.urls import url
from .views import index

from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


    # index
    url(r'^$', index, name='index'),

]

tp2ppw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_login.urls as app_login
import app_status.urls as app_status
import app_riwayat.urls as app_riwayat
import app_profile.urls as profile
import app_carimahasiswa.urls as app_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(app_login,namespace='login')),
    url(r'^status/', include(app_status,namespace='status')),
    url(r'^app-riwayat/', include(app_riwayat,namespace='app-riwayat')),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^carimahasiswa/', include(app_carimahasiswa,namespace='carimahasiswa')),
    url(r'^$', RedirectView.as_view(url = "/login/", permanent = "true"), name = 'index'),
]

app_login/models.py
from django.db import models

# Create your models here.

app_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

response = {}

def index(request):
	response['author'] = "Kelompok 5 C"
	if 'user_login' in request.session:
		response['author'] = get_data_user(request, 'user_login')
		return HttpResponseRedirect(reverse('profile:index'))
	else:
		response['author'] = get_data_user(request, 'user_login')
		html = 'app_login/login.html'
		return render(request, html, response)

def get_data_user(request, tipe):
	data = None
	if tipe == "user_login" and 'user_login' in request.session:
		data = request.session['user_login']
	return data

app_login/templates/app_login/login.html
{% extends "app_login/layout/base.html" %}
{% block content %}
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-warning"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
{% endblock %}