app_status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name='delete_status')
]

tp2ppw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_login.urls as app_login
import app_status.urls as app_status
import app_riwayat.urls as app_riwayat
import app_profile.urls as profile
import app_carimahasiswa.urls as app_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(app_login,namespace='login')),
    url(r'^status/', include(app_status,namespace='status')),
    url(r'^app-riwayat/', include(app_riwayat,namespace='app-riwayat')),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^carimahasiswa/', include(app_carimahasiswa,namespace='carimahasiswa')),
    url(r'^$', RedirectView.as_view(url = "/login/", permanent = "true"), name = 'index'),
]

app_status/models.py
from django.db import models
from app_profile import models as app_profile_models

# Create your models here.
class Status(models.Model):
	title = models.CharField(max_length=27,default = "")
	description = models.TextField(default = "")
	created_date = models.DateTimeField(auto_now_add=True)
#statuss = models.ForeignKey(app_profile_models.Pengguna, default = "")
    

app_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please write your input here',
    }
    
    description_attrs = {
        'type': 'text',
        'cols': 90,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':"Type in your status here...",
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

# class Comment_Form(forms.Form):
    # error_messages = {
        # 'required': 'Tolong isi input ini',
    # }

    # description_attrs ={
        # 'type': 'text',
        # 'cols': 60,
        # 'rows': 10,
        # 'class': 'comment-form-textarea',
        # 'placeholder':' Write your comment here. . '
    # }
    # comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

app_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form
from app_profile.models import Pengguna

# Create your views here.
response = {}

def index(request):
    if 'user_login' in request.session:
        response['login'] = True
        response['author'] = "Kelompok 5C"
        status = reversed(Status.objects.all())
        s = Status.objects.all()
        response['status'] = status
        html = 'app_status/status.html'
        response['status_form'] = Status_Form
        response['app'] = "Status"
        response['name'] = request.session['user_login']
        feed = Status.objects.all().count()
        response['feed'] = feed
        if feed>0:
            response['last'] = Status.objects.last().description
        else:
            response['last'] = 'Oops! Belum ada status'
        return render(request, html, response)
    else:
        response['login'] = False
        return HttpResponseRedirect('/login/')

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def delete_status(request, id_status):
    status = Status.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/status/')

app_status/templates/app_status/status.html
{% extends "app_riwayat/layout/base.html" %}
{% load staticfiles %}

{% block content %}
<br><br>
{% if login %}
<div class="content">
<section name="input-list" id="input-list">
    <div class="container" style="margin-left: 5%;">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            <p name="status-tagline">What's on your mind?</p>
            {% csrf_token %}
            {{ status_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-primary" value="Submit">
            <br>
        </form>
    </div>
</section>

{% endif %}
<section name="my-list" id="my-list">
    <div class="container">
    <br><br>
        <div class="flex">
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status" style="background-color: #343a40;color: white; padding: 15px; border-radius: 10px">
                            <div class="prof-pic"><img src="https://material-components-web.appspot.com/images/animal3.svg" width="50px" height="50px" style="border-radius: 50%"></div>
                            <a href="/status/delete_status/{{ data.id }}" class="close" style="margin-top: -40px;margin-right: 10px">
                                <img src="http://www.clker.com/cliparts/0/7/e/a/12074327311562940906milker_X_icon.svg.hi.png" width="20px" height="20px"></img>
                            </a>
                            <div class="name" style="font-size: 20px">{{data.name}}</div>
                            <div class="status-description" style="font-size: 18px;margin-top: 10px">
                                {{data.description}}
                            </div>
                            <div class="status-date-added" style="color: grey">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
                    <br>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Status.
            </div>
            {% endif %}
        </div>
    </div>
</section>
</div>
{% endblock %}